language: android

# Work in progress. Repo should be used for initial checkout https://github.com/osmandapp/OsmAnd-manifest/blob/master/android_build.xml

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3
    - android-27

script: ./gradlew test
